# Generated by Django 5.2 on 2025-04-05 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_choice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'exam', 'current_attempt')},
        ),
    ]
